version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: WebDockerfile
    develop:
      watch:
        - action: sync
          path: ./../../
          target: /var/www/html
          ignore:
            - node_modules
            - composer
            - .git
            - Resources
            - Modules/Media/Files
    ports:
      - "127.0.0.2:80:80"
      - "127.0.0.2:9003:9003"
    volumes:
      - ./../../:/var/www/html
    depends_on:
      - mariadb
      - redis
      - elasticsearch

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
