name: CI/CD

on: [push]

jobs:
  custom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Bash linting
      run: find ./ -type f -name '*.sh' -print0 | xargs -0 -n1 -P4 bash -n | ( grep -v "syntax error" )
